### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by rajadiky** [mrubay/claim#9]
user loginnya apa ?

**Comment by alvian1794** [comment]
izin login bang🙏

**Comment by yanto184** [comment]
Izin gabung boz....🙏🙏🙏

**Comment by nandara** [comment]
test login om

**Comment by ronigojek** [comment]
User nya apa ?

**Comment by drivermalas** [comment]
if($user == "juleha" || $user == "pieter" || $user == "asiang" || $user == "martin" || $user == "imel" || $user == "hanif" || $user == "yanto" || $user == "21")

User Login Tidak Di Encrip dan saya tau ini scrip curi curi dari mana wkwkwkwkw
